workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Set up Flutter project
        script: |
          # Create a new Flutter project
          flutter create --org uz.sabzi .
          
          # Create empty asset directories to satisfy the build
          mkdir -p assets/images
          mkdir -p assets/icons
          mkdir -p assets/fonts
          
          # Create a placeholder font file
          touch assets/fonts/Roboto-Regular.ttf
          touch assets/fonts/Roboto-Medium.ttf
          touch assets/fonts/Roboto-Bold.ttf
          
      - name: Get Flutter packages
        script: |
          flutter packages pub get
          
      - name: Build APK with reduced dependencies
        script: |
          # Build with minimal dependencies to avoid NDK version issues
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/**/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - your.shokhrukhyt05@gmail.com
