name: sabzi_app
description: A marketplace app for Uzbekistan based on the Carrot app design.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9
  google_sign_in: ^6.1.6
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # Comment out the assets section for now since we don't have actual asset files
  # assets:
  #   - assets/images/
  #   - assets/icons/
  
  # Comment out the fonts section since we don't have the actual font files
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
